version: "3.9"

services:
  odoo:
    image: odoo:18.0
    container_name: elantar_odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=qwerty76%&/
      - PROXY_MODE=True
      - WEB_BASE_URL=https://xservice.store
    volumes:
      - odoo_data:/var/lib/odoo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo_prod.rule=Host(`xservice.store`)"
      - "traefik.http.routers.odoo_prod.entrypoints=websecure"
      - "traefik.http.routers.odoo_prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.odoo_prod.loadbalancer.server.port=8069"
    networks:
      - elantar_net
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: odoo_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=qwerty76%&/
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - elantar_net
volumes:
  db_data:
  odoo_data:

networks:
  elantar_net:
    external: true
